### PR TITLE
Added Hyperlink widget

### PR DESCRIPTION
**Pull request by Shiloli-r**
Will update more soon

### CODE REVIEW

**Comment by Shiloli-r** [comment]
> Probably also bind to to allow keyboard only use.
I'll admit i had not thought anything about the keyboard only use. Will add bindings for that

**Comment by Shiloli-r** [comment]
> Is there a way you could create this font just once and then reuse instead of creating a new font object every time it is hovered. Creates unnecessary overhead. Same applies for the `_no_underline` method

Makes sense. will work on that

**Comment by Shiloli-r** [comment]
> I would have asked you to override the configure method but that shit is too messed up and needs that I writeup some standardized way of doing it. Otherwise it will result in shoddy code everywhere.

Maybe we'll organize a meet or something for more explanation on your exact plans for this configure method?

**Review by ObaraEmmanuel — APPROVED** [review]
LGTM

**Pull request merged**
